export const TABLE_KEYS = [
  'eventId',
  'ageInDays',
  'alertType',
  'animalId',
  'birthDateCalculated',
  'breedingNumber',
  'calvingEase',
  'cowEntryStatus',
  'cowId',
  'currentGroupId',
  'currentGroupName',
  'daysInLactation',
  'daysInPregnancy',
  'deletable',
  'destinationGroup',
  'destinationGroupName',
  'duration',
  'endDate',
  'endDateTime',
  'healthIndex',
  'heatIndexPeak',
  'interval',
  'isOutOfBreedingWindow',
  'lactationNumber',
  'minValueDateTime',
  'newGroupId',
  'newGroupName',
  'newborns',
  'oldLactationNumber',
  'originalStartDateTime',
  'reportingDateTime',
  'sire',
  'startDateTime',
  'type'
];

export const TABLE_HEADERS =
  ['Actions', ...TABLE_KEYS.map(key => key.replace(/([A-Z]+)/g, " $1").replace(/([A-Z][a-z])/g, " $1"))]
